spring.application.name=spring-rest

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/spring_data_jpa}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=xvZmaRYvapjQ+Vhvv59/q/arBuGON4qe+XbAPcDN7Gw=