app.environment.name=PRODUCTION

spring.datasource.url=jdbc:oracle:thin://${DB_HOST:@localhost}:${DB_PORT:1521}/inventory
spring.datasource.username=prod_user
spring.datasource.password=prod_pass
spring.datasource.driverClassName=oracle.jdbc.OracleDriver

spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
spring.jpa.hibernate.naming_strategy=org.hibernate.cfg.ImprovedNamingStrategy